config/routes.rb
Rails.application.routes.draw do
  resources :exams
  resources :animals
  resources :pet_owners
  resources :veterinaries

  # get '/pat/', to: 'patients#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/create', to: 'sessions#index'
  get '/logout', to: 'sessions#destroy'

  root 'sessions#new'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  
end

app/models/pet_owner.rb
class PetOwner < ApplicationRecord
end

app/controllers/pet_owners_controller.rb
class PetOwnersController < ApplicationController
  before_action :authenticate_user, except: []
  before_action :admin_permission, except: [ :index ]
  before_action :set_pet_owner, only: %i[ show edit update destroy ]

  # GET /pet_owners or /pet_owners.json
  def index
    @pet_owners = PetOwner.all
  end

  # GET /pet_owners/1 or /pet_owners/1.json
  def show
  end

  # GET /pet_owners/new
  def new
    @pet_owner = PetOwner.new
  end

  # GET /pet_owners/1/edit
  def edit
  end

  # POST /pet_owners or /pet_owners.json
  def create
    @pet_owner = PetOwner.new(pet_owner_params)

    respond_to do |format|
      if @pet_owner.save
        format.html { redirect_to pet_owner_url(@pet_owner), notice: "Pet owner was successfully created." }
        format.json { render :show, status: :created, location: @pet_owner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet_owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pet_owners/1 or /pet_owners/1.json
  def update
    respond_to do |format|
      if @pet_owner.update(pet_owner_params)
        format.html { redirect_to pet_owner_url(@pet_owner), notice: "Pet owner was successfully updated." }
        format.json { render :show, status: :ok, location: @pet_owner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet_owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pet_owners/1 or /pet_owners/1.json
  def destroy
    @pet_owner.destroy

    respond_to do |format|
      format.html { redirect_to pet_owners_url, notice: "Pet owner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet_owner
      @pet_owner = PetOwner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_owner_params
      params.require(:pet_owner).permit(:first_name, :last_name, :email, :cell_number)
    end
end

app/helpers/pet_owners_helper.rb
module PetOwnersHelper
end

app/views/pet_owners/_form.haml
= form_with(model: pet_owner) do |form|
  - if pet_owner.errors.any?
    %div{ style: "color: red" }
      %h2= pluralize(pet_owner.errors.count, "error") + " prohibited this pet_owner from being saved:"

      %ul
        - pet_owner.errors.each do |error|
          %li= error.full_message

  %div
    = form.label :first_name, style: "display: block"
    = form.text_field :first_name

  %div
    = form.label :last_name, style: "display: block"
    = form.text_field :last_name

  %div
    = form.label :email, style: "display: block"
    = form.text_field :email

  %div
    = form.label :cell_number, style: "display: block"
    = form.text_field :cell_number

  %div
    = form.submit

app/views/pet_owners/_pet_owner.haml
%tr{ id: dom_id(pet_owner) }
  %td
    %strong First name:
    = pet_owner.first_name
  %td
    %strong Last name:
    = pet_owner.last_name
  %td
    %strong Email:
    = pet_owner.email
  %td
    %strong Cell number:
    = pet_owner.cell_number

app/views/pet_owners/edit.haml
%h1 Editing pet owner

= render "form", pet_owner: @pet_owner

%br

%div
  = link_to "Show this pet owner", @pet_owner
  |
  = link_to "Back to pet owners", pet_owners_path

app/views/pet_owners/index.haml
%p{style: "color: green"}= notice

%h1 Pet owners

#pet_owners
  - @pet_owners.each do |pet_owner|
    = render pet_owner
    %p
      = link_to "Show this pet owner", pet_owner

.link-button
  = link_to "New pet owner", new_pet_owner_path

:javascript
  try {
    showDiv()
  } catch(err) {
  }

  addEventListener('load', () => {
    showDiv()
  })

  function showDiv () {
    const pet_owners = document.querySelector("#pet_owners")
    if (pet_owners.children.length === 0) {
      const dataNotFound = document.createElement('div')
      dataNotFound.classList.add('data-not-found')
      dataNotFound.innerHTML = 'Nenum pet owner encontrado'
      pet_owners.appendChild(dataNotFound)
    }
  }

app/views/pet_owners/new.haml
%h1 New pet owner

= render "form", pet_owner: @pet_owner

%br

%div
  = link_to "Back to pet owners", pet_owners_path

app/views/pet_owners/show.haml
%p{style: "color: green"}= notice

= render @pet_owner

%div
  = link_to "Edit this pet owner", edit_pet_owner_path(@pet_owner)
  |
  = link_to "Back to pet owners", pet_owners_path

  = button_to "Destroy this pet owner", @pet_owner, method: :delete