config/routes.rb
Rails.application.routes.draw do
  resources :exams
  resources :animals
  resources :pet_owners
  resources :veterinaries

  # get '/pat/', to: 'patients#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/create', to: 'sessions#index'
  get '/logout', to: 'sessions#destroy'

  root 'sessions#new'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :pet_owner

  validates :name, presence: true, length: {maximum: 60}
  validates :observation, presence: true, length: {maximum: 1200}
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :authenticate_user, except: []
  before_action :set_animal, only: %i[ show edit update destroy ]

  # GET /animals or /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1 or /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals or /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to animal_url(@animal), notice: "Animal was successfully created." }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1 or /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to animal_url(@animal), notice: "Animal was successfully updated." }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1 or /animals/1.json
  def destroy
    @animal.destroy

    respond_to do |format|
      format.html { redirect_to animals_url, notice: "Animal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:name, :observation, :pet_owner_id)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_animal.haml
#exam{id: "animal"}
  %p
    %strong Name:
    = animal.name
  %p
    %strong Observation:
    = animal.observation
  %p
    %strong Pet owner:
    = animal.pet_owner_id

app/views/animals/_form.haml
= form_with(model: animal) do |form|
  - if animal.errors.any?
    %div{style: "color: red"}
      %h2= pluralize(animal.errors.count, "error") + " prohibited this animal from being saved:"
      %ul
        - animal.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :name, style: "display: block"
    = form.text_field :name
  %div
    = form.label :observation, style: "display: block"
    = form.text_area :observation
  %div
    = form.label :pet_owner_id, style: "display: block"
    = form.collection_select :pet_owner_id, PetOwner.all, :id, :first_name
  %div
    = form.submit

app/views/animals/edit.haml
%h1 Editing animal

= render "form", animal: @animal

%br

%div
  = link_to "Show this animal", @animal
  |
  = link_to "Back to animals", animals_path

app/views/animals/index.haml
%p{ style: "color: green" }= notice

%h1 Animals

#animals
  - @animals.each do |animal|
    = render animal
    %p
      = link_to "Show this animal", animal

.link-button
  = link_to "New animal", new_animal_path

app/views/animals/new.haml
<h1>New animal</h1>

<%= render "form", animal: @animal %>

<br>

<div>
  <%= link_to "Back to animals", animals_path %>
</div>

app/views/animals/new.html.erb
<h1>New animal</h1>

<%= render "form", animal: @animal %>

<br>

<div>
  <%= link_to "Back to animals", animals_path %>
</div>

app/views/animals/show.haml
%h1 New animal

= render "form", animal: @animal

%br

%div
  = link_to "Back to animals", animals_path