config/routes.rb
Rails.application.routes.draw do
  resources :exams
  resources :animals
  resources :pet_owners
  resources :veterinaries

  # get '/pat/', to: 'patients#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/create', to: 'sessions#index'
  get '/logout', to: 'sessions#destroy'

  root 'sessions#new'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  
end

app/models/veterinary.rb
class Veterinary < ApplicationRecord
end

app/controllers/veterinaries_controller.rb
class VeterinariesController < ApplicationController
  before_action :authenticate_user, except: []
  before_action :set_veterinary, only: %i[ show edit update destroy ]

  before_action :admin_permission, except: [ :edit ]
  before_action :acces_permissions, only: [ :edit ]

  # GET /veterinaries or /veterinaries.json
  def index
    @veterinaries = Veterinary.all
  end

  # GET /veterinaries/1 or /veterinaries/1.json
  def show
  end

  # GET /veterinaries/new
  def new
    @veterinary = Veterinary.new
  end

  # GET /veterinaries/1/edit
  def edit
  end

  def edit_own
    render :edit
  end

  # POST /veterinaries or /veterinaries.json
  def create
    
    modified_params = veterinary_params.dup
    if password_validation(modified_params[:password], modified_params[:password_confirmation])
      modified_params[:password_digest] = Digest::SHA256.hexdigest(modified_params[:password])
      modified_params[:password] = ''
      modified_params[:password_confirmation] = ''

      modified_params.delete(:password)
      modified_params.delete(:password_confirmation)
    end
    @veterinary = Veterinary.new(modified_params)
    respond_to do |format|
      if @veterinary.save
        format.html { redirect_to veterinary_url(@veterinary), notice: "Veterinary was successfully created." }
        format.json { render :show, status: :created, location: @veterinary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @veterinary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veterinaries/1 or /veterinaries/1.json
  def update
    respond_to do |format|
      if @veterinary.update(veterinary_params)
        format.html { redirect_to veterinary_url(@veterinary), notice: "Veterinary was successfully updated." }
        format.json { render :show, status: :ok, location: @veterinary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @veterinary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veterinaries/1 or /veterinaries/1.json
  def destroy
    @veterinary.destroy

    respond_to do |format|
      format.html { redirect_to veterinaries_url, notice: "Veterinary was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def acces_permissions
      
      true if current_user.id == params[:id]
    end

    def password_validation(password, password_confirmation)
      true if password == password_confirmation && password != ''
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_veterinary
      @veterinary = Veterinary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def veterinary_params
      params.require(:veterinary).permit(:first_name,:last_name, :admin, :email, :password, :password_confirmation)
    end
end

app/helpers/veterinaries_helper.rb
module VeterinariesHelper
end

app/views/veterinaries/_form.haml
= form_with(model: veterinary) do |form|
  - if veterinary.errors.any?
    %div{ style: "color: red" }
      %h2= pluralize(veterinary.errors.count, "error") + " prohibited this veterinary from being saved:"
      %ul
        - veterinary.errors.each do |error|
          %li= error.full_message

  %div
    = form.label :first_name, style: "display: block"
    = form.text_field :first_name

  %div
    = form.label :last_name, style: "display: block"
    = form.text_field :last_name

  - if current_user.admin
    %div
      = form.label :admin, style: "display: block"
      = form.select :admin, options_for_select([["Comum", false], ["Admin", true]], veterinary.admin)

  - unless params[:id].present?
    %div
      = form.label :password, style: "display: block"
      = form.password_field :password

      %div
      = form.label :password_confirmation, style: "display: block"
      = form.password_field :password_confirmation

  %div
    = form.label :email, style: "display: block"
    = form.email_field :email

  %div
    = form.label :phone, style: "display: block"
    = form.text_field :phone

  %div
    = form.submit

app/views/veterinaries/_veterinary.haml
%tr{ id: dom_id(veterinary) }
  %td
    %strong First name:
    = veterinary.first_name

  %td
    %strong Last name:
    = veterinary.last_name

  %td
    %strong Tipo:
    = veterinary.admin ? "Admin" : "Comum"

  - if params[:id] == nil
    %td 
      .link-button
        = link_to "Show this veterinary", veterinary

app/views/veterinaries/edit.haml
%h1 Editing veterinary

= render "form", veterinary: @veterinary

%br

%div
  .link-button
    = link_to "Back to veterinaries", veterinaries_path

app/views/veterinaries/index.haml
%p{style: "color: green"}= notice

%h1 Veterinaries

- if current_user.admin 
  #veterinaries
    %table
      - @veterinaries.each do |veterinary|
        = render veterinary
        
.link-button
  = link_to "New veterinary", new_veterinary_path

app/views/veterinaries/new.haml
%h1 New veterinary

= render "form", veterinary: @veterinary

%br

%div
  .link-button
    = link_to "Back to veterinaries", veterinaries_path

app/views/veterinaries/show.haml
%p{style: "color: green"}= notice

= render @veterinary

%div
  .link-button
    = link_to "Edit this veterinary", edit_veterinary_path(@veterinary) |
  .link-button
    = link_to "Back to veterinaries", veterinaries_path
  .link-button
    = button_to "Destroy this veterinary", @veterinary, method: :delete