config/routes.rb
Rails.application.routes.draw do
  resources :exams
  resources :animals
  resources :pet_owners
  resources :veterinaries

  # get '/pat/', to: 'patients#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/create', to: 'sessions#index'
  get '/logout', to: 'sessions#destroy'

  root 'sessions#new'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :pet_owner
  belongs_to :veterinary
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :authenticate_user, except: []
  before_action :set_exam, only: %i[ show edit update destroy ]

  # GET /exams or /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1 or /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams or /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to exam_url(@exam), notice: "Exam was successfully created." }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1 or /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to exam_url(@exam), notice: "Exam was successfully updated." }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1 or /exams/1.json
  def destroy
    @exam.destroy

    respond_to do |format|
      format.html { redirect_to exams_url, notice: "Exam was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exam_params
      params.require(:exam).permit(:title, :description, :observation, :scheduled, :pet_owner_id, :veterinary_id)
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_exam.haml
#exam{id: "exam"}
  %p
    %strong Title:
    = exam.title
  %p
    %strong Description:
    = exam.description
  %p
    %strong Observation:
    = exam.observation
  %p
    %strong Scheduled:
    = exam.scheduled
  %p
    %strong Pet owner:
    = exam.pet_owner_id
  %p
    %strong Veterinary:
    = exam.veterinary_id

app/views/exams/_form.haml
= form_with(model: exam) do |form|
  - if exam.errors.any?
    %div{style: "color: red"}
      %h2= pluralize(exam.errors.count, "error") + " prohibited this exam from being saved:"
      %ul
        - exam.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :title, style: "display: block"
    = form.text_field :title
  %div
    = form.label :description, style: "display: block"
    = form.text_area :description
  %div
    = form.label :observation, style: "display: block"
    = form.text_area :observation
  %div
    = form.label :scheduled, style: "display: block"
    = form.datetime_field :scheduled
  %div
    = form.label :pet_owner_id, style: "display: block"
    = form.collection_select :pet_owner_id, PetOwner.all, :id, :first_name
  %div
    = form.label :veterinary_id, style: "display: block"
    = form.collection_select :veterinary_id, Veterinary.all, :id, :first_name
  %div
    = form.submit

app/views/exams/edit.haml
%h1 Editing exam

= render "form", exam: @exam

%br

%div
  = link_to "Show this exam", @exam
  |
  = link_to "Back to exams", exams_path

app/views/exams/index.haml
%p{ style: "color: green" }= notice

%h1 Exams

#exams
  - @exams.each do |exam|
    = render exam
    %p
      = link_to "Show this exam", exam

.link-button
  = link_to "New exam", new_exam_path

app/views/exams/new.haml
%h1 New exam

= render "form", exam: @exam

%br

%div
  = link_to "Back to exams", exams_path

app/views/exams/show.haml
%p{ style: "color: green" }= notice

= render @exam

%div
  = link_to "Edit this exam", edit_exam_path(@exam)
  |
  = link_to "Back to exams", exams_path

  = button_to "Destroy this exam", @exam, method: :delete